/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = 
{
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],*/
  
  // But you can create a sidebar manually
  tutorialSidebar : 
  [
    'Introduce',
    {
      type: 'category',
      label: 'Guide - Editor',
      items: 
      [
        'guide-editor/QuickStart',
        'guide-editor/GlobalSettings',
        'guide-editor/AssetBundleCollector',
        'guide-editor/AssetBundleBuilder',  
        'guide-editor/AssetBundleDeployer',
        'guide-editor/AssetBundleReporter',
        'guide-editor/AssetBundleDebugger',
        'guide-editor/ShaderVariantCollector',
      ],
    },
    {
      type: 'category',
      label: 'Guide - Runtime',
      items: 
      [
        'guide-runtime/CodeTutorial1',
        'guide-runtime/CodeTutorial2',
        'guide-runtime/CodeTutorial3',
        'guide-runtime/CodeTutorial4',
      ],
    },
    {
      type: 'category',
      label: 'Guide - Samples',
      items: 
      [
        'guide-samples/Samples',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: 
      [
        'community/Contributor',
        'community/CodeStyle',
        'community/Blogroll',
      ],
    },
    'FAQ',
  ],
};

module.exports = sidebars;
